site_name: Trustlines Docs
repo_name: tl-docs
repo_url: https://github.com/trustlines-protocol/tl-docs
site_description: Docs for the Trustlines Network
site_url: https://smokyish.github.io/tl-docs/docs/
edit_uri: /tl-docs/docs/
theme:
  name: material
  logo: assets/images/brand/General/SVG/trustlines-mark-logo-black.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
  palette:
    # Light mode
    - media: "(prefers-color-scheme: tl-light)"
      scheme: tl-light
      toggle:
        icon: material/weather-sunny
        name: Light

    # Dark mode
    - media: "(prefers-color-scheme: tl-dark)"
      scheme: tl-dark
      toggle:
        icon: material/weather-night
        name: Dark
  icon:
    repo: fontawesome/brands/github
  font: false
  language: en

copyright: Copyright &copy 2020-2021 Trustlines Foundation


extra_css:
  - ../tl-docs/assets/css/styles.css

extra_javascript:
  - assets/js/stats.js

extra:
  social:
    - icon: material/comment
      link: https://blog.trustlines.network/
      name: Trustlines Blog
    - icon: fontawesome/brands/discourse
      link: https://forum.trustlines.network/
      name: Trustlines Forum
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TrustlinesFound
      name: Trustlines Foundation on Twitter
    - icon: fontawesome/brands/twitter-square
      link: https://twitter.com/trustlines_app
      name: Trustlines App on Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/trustlines_network
      name: Trustlines Network community on Telegram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trustlinesnetwork/
      name: Trustlines Network on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/trustlines-protocol
      name: Trustlines Protocol on GitHub
  homepage: https://trustlines.network/
  alternate:
    - name: English
      link: /en/docs/
      lang: en
    - name: Español
      link: /docs/index.es
      lang: es

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - meta
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
        - es
  - i18n:
      languages:
        es: "Español"
        en: "English"
      default_language: 'en'
      no_translation:
        en: "This page isn't translated to English."
        es: "Esta página no está traducida al español."
      translate_nav:
        en:
          section title: "Trustlines App Guide"
          subsection: "Whitepaper"
          page title: "Page with title translated"
        es:
          section title: "asdf"
          subsection: "Subsección"
          page title: "Página con título traducido"


nav:
  - Trustlines Docs: docs/index.md
  - Whitepaper:
    - Abstract: docs/resources/wp_content/abstract.md
    - How Trustlines works: docs/resources/wp_content/how_trustlines_works.md
    - Use in the real world: docs/resources/wp_content/use_in_the_real_world.md
  - Guides:
    - Trustlines App Guide: docs/guides/tl_app_user_guide.md
    - How to claim TLN from the Merkle Drop: docs/guides/how_to_claim_tln.md
    - How to withdraw your validator deposit: docs/guides/how_to_withdraw_validator_deposit.md
    - Converting TLN to TLC: docs/guides/converting_tln_to_tlc.md
    - Communications Guide: docs/resources/community_communications_guide.md
  - Use Cases:
    - Time Credits / Time Banking:
      - Time Credits on Trustlines: docs/use_cases/time_credits/time_credits_on_trustlines.md
      - Time Credits - User Stories: docs/use_cases/time_credits/time_credits_user_stories.md
    - Bill splitting:
      - Bill splitting on Trustlines: docs/use_cases/bill_splitting/bill_splitting_on_trustlines.md
  - Brand:
    - Brand Guidelines: docs/brand/brand_guidelines.md
    - Brand Resources: docs/brand/brand_resources.md
  - FAQ: docs/resources/FAQ.md
  - Community:
    - Glossary: docs/resources/glossary.md
    - Presentations: docs/resources/presentations/presentation_slides.md
  - Legal:
    - Trustlines Trademark Guidelines: docs/foundation/trademarks.md
